### ISSUE TITLE
Error while pruning

### ISSUE THREAD

**Issue by chrismaragkos** [Catglobe/Openiddict.contrib#9]
I get this exception in openiddict 5.x 
System.MissingMethodException: Method not found: 'System.Threading.Tasks.ValueTask OpenIddict.Abstractions.IOpenIddictAuthorizationManager.PruneAsync(System.DateTimeOffset, System.Threading.CancellationToken)'. at Openiddict.Contrib.Pruning.BackgroundService.OpenIddictPruningBackgroundService.PruneAsync(CancellationToken cancellationToken) at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Openiddict.Contrib.Pruning.BackgroundService.OpenIddictPruningBackgroundService.PruneAsync(CancellationToken cancellationToken) at Openiddict.Contrib.Pruning.BackgroundService.OpenIddictPruningBackgroundService.ExecuteAsync(CancellationToken stoppingToken)

"Catglobe.Openiddict.Contrib.Pruning.BackgroundService": "1.7.0"

Do I need some upgrade or I'm something missing in my setup.

**Comment by davhdavh** [comment]
Openiddict.contrib is only compatible with 4.x for now. Please reopen if it is still an issue there

**Comment by davhdavh** [comment]
I have released v5.0.0 which uses openiddict 5.5.0
